--CREATE DATABASE RacedayDB;

--CREATE TABLE Users (
--UserID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
--Name VARCHAR(30) NOT NULL,
--Surname VARCHAR(30) NOT NULL,
--Access VARCHAR(30) NOT NULL CHECK (Access IN ('Organiser', 'Participant')),
--Password VARCHAR(50) NOT NULL
--);

CREATE TABLE Category(
CategoryID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
CategoryName VARCHAR(30) NOT NULL,
);

CREATE TABLE Event(
EventID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
CategoryID INT FOREIGN KEY REFERENCES Category(CategoryID),
EventName VARCHAR(30) NOT NULL,
Location VARCHAR(50) NOT NULL,
Description VARCHAR(50) NOT NULL,
Date DATE NOT NULL,
Type VARCHAR(50) NOT NULL
);

