--CREATE DATABASE RacedayDB;

CREATE TABLE Users (
UserID INT IDENTITY(1,1)  NOT NULL PRIMARY KEY,
Name VARCHAR(30) NOT NULL,
Surname VARCHAR(30) NOT NULL,
Access VARCHAR(30) NOT NULL CHECK (Access IN ('Organiser', 'Participant')),
Password VARCHAR(50) NOT NULL
);

